(() => {
const {games,clues,puzzles}=window.GAMEGRID_DATA;
const $=s=>document.querySelector(s); const todayISO=()=>new Date().toISOString().slice(0,10);
const latestAvailable=()=>puzzles.filter(p=>p.date<=todayISO()).at(-1)||puzzles[0];
let puzzle=latestAvailable(),selected=null,tick=null;
const key=p=>`gamegrid:${p.id}`;
const fresh=()=>({answers:Array(9).fill(null),guesses:9,started:Date.now(),finished:false,gaveUp:false});
let state=load();
function load(){try{return {...fresh(),...JSON.parse(localStorage.getItem(key(puzzle))||'{}')}}catch{return fresh()}}
function save(){localStorage.setItem(key(puzzle),JSON.stringify(state));}
function clue(id){return clues[id]}
function initials(title){return title.split(/\s+/).filter(x=>!['the','of','a','and'].includes(x.toLowerCase())).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function qualifies(game,r,c){return clue(puzzle.rows[r]).test(game)&&clue(puzzle.cols[c]).test(game)}
function render(){
 $('#puzzleTitle').textContent=`GameGrid #${puzzle.id}`; $('#modeLabel').textContent=`DAILY ${puzzle.mode.toUpperCase()}`; $('#puzzleDate').textContent=new Date(puzzle.date+'T12:00:00').toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long'}); $('#guessesLeft').textContent=state.guesses;
 const grid=$('#grid');grid.innerHTML='<div class="clue corner">×</div>';
 puzzle.cols.forEach(id=>grid.insertAdjacentHTML('beforeend',`<div class="clue">${clue(id).label}</div>`));
 puzzle.rows.forEach((rid,r)=>{grid.insertAdjacentHTML('beforeend',`<div class="clue">${clue(rid).label}</div>`);puzzle.cols.forEach((cid,c)=>{const i=r*3+c,g=games.find(x=>x.id===state.answers[i]);const b=document.createElement('button');b.className=`cell ${g?'solved':'empty'}`;b.dataset.i=i;b.disabled=state.finished&&!g;b.setAttribute('aria-label',g?`${g.title}. ${clue(rid).label} and ${clue(cid).label}`:`Answer ${clue(rid).label} and ${clue(cid).label}`);if(g)b.innerHTML=`<span class="cover">${initials(g.title)}</span><span class="cell-title">${g.title}</span>`;b.onclick=()=>g?showGame(g,r,c):openSearch(i,r,c);grid.appendChild(b)})});
 const solved=state.answers.filter(Boolean).length;$('#solvedCount').textContent=`${solved} / 9`;if(solved===9&&!state.finished)finish(false);renderStats();
}
function openSearch(i,r,c){if(state.finished||state.guesses<=0)return;selected={i,r,c};$('#searchClue').textContent=`${clue(puzzle.rows[r]).label} + ${clue(puzzle.cols[c]).label}`;$('#gameSearch').value='';showResults('');$('#searchDialog').showModal();setTimeout(()=>$('#gameSearch').focus(),80)}
function normalise(s){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ')}
function showResults(q){const nq=normalise(q);let list=games.filter(g=>!state.answers.includes(g.id));if(nq)list=list.map(g=>({g,score:normalise(g.title).startsWith(nq)?0:normalise(g.title).includes(nq)?1:2})).filter(x=>x.score<2).sort((a,b)=>a.score-b.score||a.g.title.localeCompare(b.g.title)).map(x=>x.g);else list=list.slice().sort((a,b)=>b.year-a.year);list=list.slice(0,18);$('#searchResults').innerHTML=list.map(g=>`<button class="result" data-id="${g.id}"><span class="mini-cover">${initials(g.title)}</span><span><strong>${g.title}</strong><small>${g.year} · ${g.platforms.slice(0,3).join(', ')}</small></span></button>`).join('')||'<p class="muted">No games found.</p>';document.querySelectorAll('.result').forEach(b=>b.onclick=()=>submit(b.dataset.id))}
function submit(id){const g=games.find(x=>x.id===id),{i,r,c}=selected;state.guesses--;if(qualifies(g,r,c)){state.answers[i]=id;toast('Correct ✓');$('#searchDialog').close()}else{toast(`${g.title} doesn't match both clues`);if(state.guesses<=0){$('#searchDialog').close();finish(true)}}save();render()}
function finish(gaveUp){state.finished=true;state.gaveUp=gaveUp;save();updateLifetime();render();showResultsDialog()}
function updateLifetime(){const k='gamegrid:stats';let s=JSON.parse(localStorage.getItem(k)||'{"played":0,"wins":0,"streak":0,"best":0,"completed":[]}');if(s.completed.includes(puzzle.id))return;s.played++;const win=state.answers.filter(Boolean).length===9;if(win){s.wins++;s.streak++;s.best=Math.max(s.best,s.streak)}else s.streak=0;s.completed.push(puzzle.id);localStorage.setItem(k,JSON.stringify(s))}
function showResultsDialog(){const solved=state.answers.filter(Boolean).length;const secs=Math.floor(((state.ended||Date.now())-state.started)/1000);state.ended=state.ended||Date.now();save();const emoji=state.answers.map(x=>x?'🟩':'⬛').reduce((a,x,i)=>a+x+(i%3===2?'\n':''),'');$('#infoTitle').textContent=`GameGrid #${puzzle.id} results`;$('#infoBody').innerHTML=`<div class="result-grid">${state.answers.map(x=>`<div class="result-square ${x?'':'miss'}">${x?'✓':'·'}</div>`).join('')}</div><p><strong>${solved}/9</strong> solved · ${formatTime(secs)}</p><p class="muted">Global rarity is not shown because this static GitHub Pages version has no legitimate global answer database.</p><button class="primary-btn" id="shareBtn">Copy results</button>`;$('#infoDialog').showModal();$('#shareBtn').onclick=async()=>{const text=`GAMEGRID #${puzzle.id}\n\n${emoji}\n${solved}/9 · ${formatTime(secs)}`;await navigator.clipboard.writeText(text);toast('Results copied')};}
function showGame(g,r,c){$('#infoTitle').textContent=g.title;$('#infoBody').innerHTML=`<p><strong>${g.year}</strong></p><p>${g.developers.join(', ')} · ${g.publishers.join(', ')}</p><p class="muted">${g.platforms.join(' · ')}</p><hr><p>✓ ${clue(puzzle.rows[r]).label}<br>✓ ${clue(puzzle.cols[c]).label}</p>`;$('#infoDialog').showModal()}
function formatTime(s){return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function renderArchive(){const el=$('#archiveList');el.innerHTML=puzzles.filter(p=>p.date<=todayISO()).slice().reverse().map(p=>`<button class="archive-item" data-id="${p.id}"><strong>GameGrid #${p.id}</strong><span>${new Date(p.date+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}</span></button>`).join('');el.querySelectorAll('button').forEach(b=>b.onclick=()=>{puzzle=puzzles.find(p=>p.id==b.dataset.id);state=load();switchView('today');render()})}
function getStats(){return JSON.parse(localStorage.getItem('gamegrid:stats')||'{"played":0,"wins":0,"streak":0,"best":0}')}
function renderStats(){const s=getStats();$('#statsCards').innerHTML=[['Played',s.played],['Win rate',s.played?Math.round(s.wins/s.played*100)+'%':'0%'],['Current streak',s.streak],['Best streak',s.best],['Daily grids',puzzles.filter(p=>p.date<=todayISO()).length],['Games indexed',games.length]].map(([l,v])=>`<div class="stat"><strong>${v}</strong><span>${l}</span></div>`).join('')}
function switchView(v){['game','archive','stats'].forEach(x=>$(`#${x}View`)?.classList.toggle('hidden',x!==v));document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===v));if(v==='archive')renderArchive();if(v==='stats')renderStats()}
$('#gameSearch').addEventListener('input',e=>showResults(e.target.value));$('#giveUpBtn').onclick=()=>{if(!state.finished&&confirm('Give up this grid and reveal your result?'))finish(true)};$('#helpBtn').onclick=()=>{$('#infoTitle').textContent='How to play';$('#infoBody').innerHTML='<p>Find a video game that matches <strong>both clues</strong> for each square.</p><p>You have nine guesses to complete all nine squares. An incorrect answer uses a guess. A game can only be used once per grid.</p><p>Your daily progress and statistics are stored on this device.</p>';$('#infoDialog').showModal()};
document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>switchView(b.dataset.view==='today'?'game':b.dataset.view));
const preferred=localStorage.getItem('gamegrid:theme')|| (matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');document.documentElement.dataset.theme=preferred;$('#themeBtn').onclick=()=>{const t=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=t;localStorage.setItem('gamegrid:theme',t)};
function timer(){if(!state.finished)$('#timer').textContent=formatTime(Math.floor((Date.now()-state.started)/1000));else $('#timer').textContent=formatTime(Math.floor(((state.ended||Date.now())-state.started)/1000))}tick=setInterval(timer,1000);timer();render();
})();