(() => {
  const DATA=window.GAMEGRID_DATA;if(!DATA)return;
  const {games,clues,puzzles}=DATA,$=s=>document.querySelector(s);
  const NINTENDO=new Set(['Switch','Switch 2','Wii U','Wii','GameCube','Nintendo 64','SNES','NES','Game Boy Advance','Game Boy Color','Game Boy','Nintendo DS','Nintendo 3DS','Nintendo platform']);
  function currentMode(){return document.querySelector('.mode-tab.active')?.dataset.mode||'Classic'}
  function currentPuzzle(){const id=Number((($('#puzzleTitle')?.textContent||'').match(/#(\d+)/)||[])[1]);const mode=currentMode();return puzzles.find(p=>p.id===id&&p.mode===mode)||puzzles.find(p=>p.id===id)||null}
  function stateFor(p){try{return JSON.parse(localStorage.getItem(`gamegrid:${p.mode}:${p.id}`)||'{}')}catch{return {}}}
  function scopeOK(g,p){if(p.scope==='Retro')return g.year<=2009;if(p.scope==='Nintendo')return g.platforms.some(x=>NINTENDO.has(x));if(p.scope==='PlayStation')return g.platforms.some(x=>x.startsWith('PlayStation')||['PSP','PS Vita'].includes(x));if(p.scope==='Xbox')return g.platforms.some(x=>x.startsWith('Xbox'));return true}
  function qualifies(g,p,r,c){return scopeOK(g,p)&&clues[p.rows[r]].test(g)&&clues[p.cols[c]].test(g)}
  function engagement(g){return Number(g.ratingsCount||0)}
  const poolCache=new Map();
  function poolFor(p,r,c){const k=`${p.mode}:${p.id}:${r}:${c}`;if(poolCache.has(k))return poolCache.get(k);const pool=games.filter(g=>qualifies(g,p,r,c)).sort((a,b)=>engagement(b)-engagement(a)||String(a.title).localeCompare(String(b.title)));poolCache.set(k,pool);return pool}
  function rarityFor(g,p,r,c){const pool=poolFor(p,r,c);if(!pool.length)return null;const value=engagement(g),lower=pool.filter(x=>engagement(x)<value).length,equal=pool.filter(x=>engagement(x)===value).length;return Math.round(((lower+equal*.5)/pool.length)*1000)/10}
  function metrics(p,state){let score=0,solved=0;const rarities=[];for(let i=0;i<9;i++){const g=games.find(x=>x.id===state?.answers?.[i]);if(!g){score+=100;rarities.push(null);continue}const rar=rarityFor(g,p,Math.floor(i/3),i%3);rarities.push(rar);score+=Number.isFinite(rar)?rar:100;solved++}return {score:Math.round(score),solved,rarities,avg:solved?Math.round(rarities.filter(Number.isFinite).reduce((a,b)=>a+b,0)/solved*10)/10:null}}
  function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
  function cover(g){return g?.coverUrl?`<img src="${esc(g.coverUrl)}" alt="" loading="lazy">`:`<span>${esc((g?.title||'?').slice(0,2).toUpperCase())}</span>`}
  function playerPicks(p,state){return Array.from({length:9},(_,i)=>games.find(g=>g.id===state?.answers?.[i])||null)}
  function reference(p,best=false){return Array.from({length:9},(_,i)=>{const pool=poolFor(p,Math.floor(i/3),i%3);return best?pool.at(-1):pool[0]})}
  function answerGrid(title,sub,picks,p,player=false){return `<section class="answer-grid-block"><div class="reference-head"><h3>${title}</h3><p>${sub}</p></div><div class="answer-grid">${picks.map((g,i)=>{const rar=g?rarityFor(g,p,Math.floor(i/3),i%3):null;return `<button class="answer-cell${!g?' empty-answer':''}" ${g?`data-answer-cell="${i}" data-game-id="${esc(g.id)}"`:''}><div class="answer-art">${g?cover(g):'<span>?</span>'}</div><div class="answer-copy"><strong>${g?esc(g.title):'Unanswered'}</strong><small>${rar==null?'100 point penalty':`${rar} rarity points`}</small></div></button>`}).join('')}</div></section>`}
  function persist(p,state,m){state.rarities=m.rarities;state.score=m.score;state.avgRarity=m.avg;localStorage.setItem(`gamegrid:${p.mode}:${p.id}`,JSON.stringify(state))}
  function allAnswersHTML(p,cell,q=''){const r=Math.floor(cell/3),c=cell%3,pool=poolFor(p,r,c),term=q.trim().toLowerCase(),filtered=term?pool.filter(g=>g.title.toLowerCase().includes(term)):pool;return `<div class="valid-head"><span>${esc(clues[p.rows[r]].label)} + ${esc(clues[p.cols[c]].label)}</span><strong>${pool.length} valid answers</strong></div><div class="valid-list">${filtered.slice(0,150).map(g=>`<div class="valid-answer">${cover(g)}<div><strong>${esc(g.title)}</strong><small>${rarityFor(g,p,r,c)} rarity points</small></div></div>`).join('')||'<p class="muted">No matching titles.</p>'}</div>${filtered.length>150?`<p class="muted">Showing first 150 of ${filtered.length}. Search to narrow the list.</p>`:''}`}
  function openAllAnswers(p){const body=$('#infoBody'),title=$('#infoTitle');title.textContent='All valid answers';body.innerHTML=`<div class="answer-browser"><label class="answer-browser-search"><span>⌕</span><input id="validAnswerSearch" type="search" placeholder="Search valid answers…" autocomplete="off"></label><div class="cell-picker">${Array.from({length:9},(_,i)=>`<button data-valid-cell="${i}" class="${i===0?'active':''}">${i+1}</button>`).join('')}</div><div id="validAnswerResults"></div></div>`;let cell=0;const render=()=>$('#validAnswerResults').innerHTML=allAnswersHTML(p,cell,$('#validAnswerSearch').value);render();body.querySelectorAll('[data-valid-cell]').forEach(b=>b.onclick=()=>{body.querySelectorAll('[data-valid-cell]').forEach(x=>x.classList.toggle('active',x===b));cell=+b.dataset.validCell;render()});$('#validAnswerSearch').oninput=render}
  function enhance(){const dialog=$('#infoDialog'),body=$('#infoBody'),title=$('#infoTitle');if(!dialog?.open||!/results/i.test(title?.textContent||'')||body.querySelector('.postgame-v2'))return;const p=currentPuzzle(),state=stateFor(p);if(!p||!state.finished)return;const m=metrics(p,state);persist(p,state,m);const yours=playerPicks(p,state),obvious=reference(p),best=reference(p,true);body.innerHTML=`<div class="postgame-v2"><section class="end-hero"><span class="eyebrow">GRID COMPLETE</span><h2>${m.score} points</h2><p class="end-verdict">${m.score<=150?'Ridiculously obscure.':m.score<=300?'Deep cuts. Very nicely played.':m.score<=500?'Strong grid. You dodged plenty of obvious picks.':m.score<=700?'Solid finish. There are rarer answers hiding in there.':'You got through it. Now hunt the deep cuts.'}</p><div class="end-meta"><span><strong>${m.solved}/9</strong> solved</span><span><strong>${m.avg??'–'}</strong> avg rarity</span><span>Lower is better</span></div></section>${answerGrid('Your completed grid','Every answer, with the rarity points it contributed to your final score.',yours,p,true)}<div class="reference-tabs"><button class="active" data-ref="obvious">Most obvious</button><button data-ref="best">Best rarity</button></div><div id="referenceStage">${answerGrid('Most obvious grid','The highest-popularity valid answer in every square.',obvious,p)}</div><template id="obviousGrid">${answerGrid('Most obvious grid','The highest-popularity valid answer in every square.',obvious,p)}</template><template id="bestGrid">${answerGrid('Best rarity grid','The lowest-popularity valid answer in every square.',best,p)}</template><section class="postgame-actions"><button class="primary-btn" id="postgameShare">Share my ${m.score}-point grid</button><button class="secondary-btn" id="viewValidAnswers">View all valid answers</button></section><p class="rarity-note">Rarity is currently estimated from ratings-count popularity within each square's valid answer pool. Lower is better. An unanswered square costs 100 points.</p></div>`;body.querySelectorAll('[data-ref]').forEach(b=>b.onclick=()=>{body.querySelectorAll('[data-ref]').forEach(x=>x.classList.toggle('active',x===b));$('#referenceStage').innerHTML=(body.querySelector(`#${b.dataset.ref}Grid`)||body.querySelector('#obviousGrid')).innerHTML});$('#viewValidAnswers').onclick=()=>openAllAnswers(p);$('#postgameShare').onclick=()=>window.dispatchEvent(new CustomEvent('gamegrid:share-result',{detail:{score:m.score,solved:m.solved,rarity:m.avg}}))}
  const obs=new MutationObserver(enhance);obs.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['open']});document.addEventListener('click',()=>setTimeout(enhance,0));
})();