(() => {
  const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));
  function currentMode(){const a=document.querySelector('.mode-tab.active');return a?.dataset.mode||a?.textContent?.trim()||'Classic'}
  function currentPuzzleId(){return ((($('#puzzleTitle')?.textContent||'').match(/#(\d+)/)||[])[1]||'')}
  function puzzleUrl(){const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('mode',currentMode());u.searchParams.set('puzzle',currentPuzzleId());return u.toString()}
  function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
  async function nativeOrCopy({title,text,url,label='Copied'}){try{if(navigator.share){await navigator.share({title,text,url});return true}}catch(e){if(e?.name==='AbortError')return true}const payload=[text,url].filter(Boolean).join('\n\n');try{await navigator.clipboard.writeText(payload);toast(label);return true}catch{window.prompt('Copy this:',payload);return true}}
  async function shareGrid(){return nativeOrCopy({title:`GameGrid ${currentMode()} #${currentPuzzleId()}`,text:`🎮 Today's GameGrid challenge\n${currentMode()} #${currentPuzzleId()}\n\nNine squares. Nine games. How low can you score?`,url:puzzleUrl(),label:'Challenge link copied'})}
  window.GameGridShare={shareGrid,puzzleUrl};
  function state(){try{return JSON.parse(localStorage.getItem(`gamegrid:${currentMode()}:${currentPuzzleId()}`)||'{}')}catch{return {}}}
  function resultText(detail={}){const s=state(),score=detail.score??s.score,rarity=detail.rarity??s.avgRarity,solved=detail.solved??(s.answers||[]).filter(Boolean).length;let grid='';for(let i=0;i<9;i++){grid+=(s.answers?.[i]?'🟩':'⬛');if(i%3===2)grid+='\n'}const scoreLine=Number.isFinite(score)?`${score} points · lower is better`:'Game complete';const hook=score<=150?'Deep cuts only. Can you go lower?':score<=300?'Think you can find rarer answers?':score<=500?'Can you beat my rarity score?':'Surely you can beat this score…';return `🎮 GAMEGRID ${currentMode().toUpperCase()} #${currentPuzzleId()}\n\n${grid}\n${scoreLine}\n${solved}/9 solved${Number.isFinite(rarity)?` · ${rarity} avg rarity`:''}\n\n${hook}`}
  function shareResult(detail={}){nativeOrCopy({title:`GameGrid ${currentMode()} #${currentPuzzleId()} · ${detail.score??state().score} points`,text:resultText(detail),url:puzzleUrl(),label:'Result copied'})}
  $('#topShareBtn')?.addEventListener('click',shareGrid);
  window.addEventListener('gamegrid:share-result',e=>shareResult(e.detail||{}));
  function enhanceResults(){const dialog=$('#infoDialog'),body=$('#infoBody');if(!dialog?.open||!/results/i.test($('#infoTitle')?.textContent||''))return;const old=$('#shareBtn');if(old&&!old.dataset.native){old.dataset.native='1';old.textContent=navigator.share?'Share result':'Copy result';old.onclick=()=>shareResult()}}
  async function restoreSharedPuzzle(){const q=new URLSearchParams(location.search),mode=q.get('mode'),puzzle=q.get('puzzle');if(!mode||!puzzle)return;await sleep(80);const b=[...document.querySelectorAll('.mode-tab')].find(x=>(x.dataset.mode||x.textContent.trim()).toLowerCase()===mode.toLowerCase());if(b&&!b.classList.contains('active')){b.click();await sleep(80)}if(($('#puzzleTitle')?.textContent||'').includes(`#${puzzle}`))return;document.querySelector('.nav-btn[data-view="archive"]')?.click();await sleep(60);const item=document.querySelector(`#archiveList .archive-item[data-id="${CSS.escape(puzzle)}"]`);if(item)item.click();else{document.querySelector('.nav-btn[data-view="today"]')?.click();toast('That shared puzzle is not available')}}
  new MutationObserver(enhanceResults).observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['open']});restoreSharedPuzzle();
})();